### ISSUE TITLE
Move away from using `assert()` and instead expose ENOENT

### ISSUE THREAD

**Issue by Fishrock123** [nodesource/universal-module-tree#12]
When `node_modules` and/or a `package-lock.json` does not exist, the error produced is not very good and quite artificial. It would be nicer to handle an `ENOENT` more directly with this additional `"please run npm install"` information tacked on, I think.

Even throwing a custom error perhaps with the code set correctly.

Refs: https://github.com/nodesource/ncm-cli/issues/178

**Comment by juliangruber** [comment]
An ENOENT would be artificial here too, as we don't get one. I'll update this to throw an error with a proper code.

**Comment by juliangruber** [comment]
https://github.com/nodesource/universal-module-tree/pull/13
